routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Home\IndexController@index');

Auth::routes();
Route::post('register/users','Register\RegisterUsersController@createUsers')->name('users.register');
Route::get('/home', 'HomeController@index')->name('home');
//Route::get('auth/redirect', 'Auth\LoginController@redirectToProvider');
//Route::get('auth/callback', 'Auth\LoginController@handleProviderCallback');

/* Admin Route */
Route::prefix('admin')->group(function() {
    Route::get('/login',
    'Admin\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Admin\AdminLoginController@login')->name('admin.login.submit');
    Route::get('logout/', 'Admin\AdminLoginController@logout')->name('admin.logout');
     
    Route::get('/', 'Admin\AdminController@index')->name('admin.dashboard');
     /* For admin merchant routes */
     Route::get('/merchants','Admin\AdminMerchantController@showMerchants')->name('admin.merchants');
     Route::get('/getindexmerchants','Admin\AdminMerchantController@indexMerchants')->name('merchants.index');
     Route::get('/merchants/create','Admin\AdminMerchantController@showForm')->name('create.merchant');
     Route::post('/merchants/create','Admin\AdminMerchantController@storeMerchant')->name('store.merchant');   

     /* For admin categories routes */
     Route::get('/getindexcategories','Admin\AdminCategoriesController@indexCategories')->name('index.categories');
     Route::get('/categories/create','Admin\AdminCategoriesController@showFormCategory')->name('create.categories');
     Route::post('/categories/create','Admin\AdminCategoriesController@storeCategory')->name('store.categories');
     Route::get('/categories','Admin\AdminCategoriesController@showCategories')->name('admin.categories');
     /* End admin categories routes */

     /* For admin vouchers routes */
     Route::get('/vouchers','Admin\AdminVoucherController@indexVouchers')->name('admin.vouchers');
     Route::get('/vouchers/create','Admin\AdminVoucherController@showFormVouchers')->name('create.vouchers');
     Route::post('/vouchers/store','Admin\AdminVoucherController@storeVouchers')->name('store.vouchers');
     /* End Admin Vouchers controller */   
    }); 
/* End Admin Route */

/* Merchants Back End Route */
Route::prefix('merchant')->group(function() {
    Route::get('/login',
    'Merchant\MerchantLoginController@showLoginForm')->name('merchant.loginform');
    Route::get('/', 'Merchant\MerchantController@index')->name('merchant.dashboard');
    Route::post('/login', 'Merchant\MerchantLoginController@login')->name('merchant.submit');
    Route::get('logout/', 'Merchant\MerchantLoginController@logout')->name('merchant.logout');
    Route::get('/reset','Merchant\ResetPasswordController@resetView')->name('merchant.resetpassword');
    Route::post('/reset','Merchant\ResetPasswordController@saveData')->name('forget.password.merchant');
}); 

/* End Merchants Back End Route */

Route::get('/landingpage', function(){
    return view('layouts.landinglogin');
    });
Route::get('/vouchers/{slug}','Home\IndexController@showDetails');
Route::get('shop/all', 'Home\IndexController@shopAll');
Route::delete('emptyCart', 'Cart\CartController@emptyCart');
Route::get('checkout','Cart\CartController@checkOut');
Route::resource('cart','Cart\CartController');
Route::get('myvouchers/{id}',['uses' => 'HomeController@myVouchers', 'middleware' => 'AuthResource','name' => 'CustomerVouchers']);
Route::get('myvouchers/details/{uniqueCode}','HomeController@myVoucherDetails');
Route::post('/redeem/?u={kode_unik}','Merchant\RedeemController@redeemVoucher');
Route::get('/redeem','Merchant\RedeemController@redeemView')->name('redeem');
Route::post('/redeem','Merchant\RedeemController@redeemVoucherForm')->name('redeemed');

Route::prefix('users')->group(function() {
    Route::get('/profile/{id}',
    'Merchant\MerchantLoginController@showLoginForm')->name('merchant.loginform');
}); 
Route::Auth();

resources/views/layouts/_include/carousel.blade.php
<div class="row">
<div class="col-md-12">

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100 img-fluid" src="{{ asset('img/promotion1.jpeg') }}" alt="First slide">
    </div>
    <div class="carousel-item img-fluid">
      <img class="d-block w-100" src="{{ asset('img/promotion2.jpeg') }}" alt="Second slide">
    </div>
    <div class="carousel-item img-fluid">
      <img class="d-block w-100" src="{{ asset('img/promotion3.jpeg') }}" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>
</div>

resources/views/layouts/_include/g_analytics.blade.php
<!-- Google Analythics -->
<script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-100600572-1', 'auto');
      ga('send', 'pageview');
     
     
</script>

resources/views/layouts/_include/head.blade.php
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

<!-- Seo Meta -->
<meta name="description" content="Narahub menyediakan deal dan promo terbaik seperti voucher laptop dan accessories, voucher smartphone, komputer, lelang sparepart dan masih banyak lagi di Indonesia">
<meta name="keywords" content="Nara, Hub, Narahub, Hubungan, Diskon, Discount, Indonesia, Gadget,
Voucher, Food, Kupon, Promo, Notebook, Smartphone, Jawa Barat, DKI Jakarta,
Surabaya">
<meta property="og:title" content="Narahub | Indonesia's best deals and auctions" />
<meta property="og:type" content="e-commerce" />
<meta property="og:url" content="https://www.narahub.com/" />
<meta property="og:image" content="https://dwj199mwkel52.cloudfront.net/assets/social/home_facebook_card-c24af70e1ea78ec96cdf28f926fc76eb3ce3ecaf973042255492aa1de7727393.jpg" />
<meta property="og:description" content="Narahub is online platform that providing deals in surabaya and auction in indonesia" />
<meta property="og:site_name" content="Narahub" />




<!-- CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}">

resources/views/layouts/_include/header.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  
</head>
<style>
     .navbar-brand{
        font-family: 'Pacifico', cursive;
        font-size : 24px;
      }

      .nav-link{
        font-size : 16px;
      }
    </style>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-narahub-accent sticky-top">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
  <ul class="navbar-nav">
<a class="navbar-brand" href="#"><img src="{{ asset('img/logo.png') }}" alt="Servis Now" style="width: 50px; height: 50px; font-family: 'Pacifico', cursive;">&nbsp <label style="color:white;">Narahub</label></a>

  </ul>  
  <ul class="navbar-nav ml-auto">
  <form class="form-inline">
    <input class="form-control" type="search" placeholder="Search" aria-label="Search">
    &nbsp <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>
  </form>

  </ul>
  @auth
  <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{{ url('/') }}" style="color:white;">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url('/users/profile') }}" style="color:white;">Profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url('myvouchers' ,Auth::user()->id) }}" style="color:white;">My Vouchers</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url('shop/all') }}" style="color:white;">Vouchers</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" style="color:white;">Article</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ route('cart.index') }}" style="color:white;"><i class="fas fa-shopping-bag"></i>Cart<span class="badge badge-pill badge-danger" id="cart-value">{{ Cart::getContent()->count() }}</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url('/users/setting') }}" style="color:white;">Settings</a>
      </li>
      <li class="nav-item">
      <form id="logout-form" action="{{ route('logout') }}" method="POST">
      {{ csrf_field() }}
        <button type="submit" value="Logout" class="btn btn-danger btn-lg">Logout</button>
        </form>
      </li>
     
     
    
      
</ul>
@endauth
  @guest
  <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{{ url('/') }}" style="color:white;">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" style="color:white;">Lelang</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url('shop/all') }}" style="color:white;">Vouchers</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" style="color:white;">Article</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ route('cart.index') }}" style="color:white;"><i class="fas fa-shopping-bag"></i>My Bag<span class="badge badge-pill badge-danger" id="cart-value">{{ Cart::getContent()->count() }}</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link btn btn-info" href="{{ url('/register') }}" style="color:white; border-radius: 10px;">Sign Up</a>
      </li>
      &nbsp;
      
      <li class="nav-item">
        <a class="nav-link btn btn-success" href="{{ url('/landingpage') }}" style="color:white; border-radius: 10px;">Login</a>
      </li>
</ul>
@endguest
  </div>
</nav>
</body>
</html>

resources/views/layouts/_include/plugin.blade.php
<script src="{{ asset('js/jquery-3.3.1.min.js') }}"></script>
<script src="{{ asset('js/popper.min.js') }}"></script>
<script src="{{ asset('js/bootstrap-4.1.3.min.js') }}"></script>
<script src="{{ asset('js/moment.js') }}"></script>
<script src="{{ asset('js/jquery.dataTables.min.js') }}"></script>  
<script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script src="{{ asset('js/notify.min.js') }}"></script>
<script src="{{ asset('js/jquery.countdown.min.js') }}"></script>
<script src="{{ asset('js/custom/custom.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/locale/id.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/standalone/selectize.min.js"></script>
<script src="//unpkg.com/jscroll/dist/jquery.jscroll.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.10/summernote.min.js"></script>

resources/views/layouts/_include/testimoni.blade.php
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" height="500px">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
    <img src="{{ asset('img/cover.png') }}" alt="...">
  <div class="carousel-caption d-none d-md-block">
    <h5>...</h5>
    <p>...</p>
    </div>
    <div class="carousel-item img-fluid">
    <img src="{{ asset('img/cover.png') }}" alt="...">
  <div class="carousel-caption d-none d-md-block">
    <h5>...</h5>
    <p>...</p>
    </div>
    <div class="carousel-item img-fluid">
    <img src="{{ asset('img/cover.png') }}" alt="...">
  <div class="carousel-caption d-none d-md-block">
    <h5>...</h5>
    <p>...</p>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>